(function(){
  'use strict';
  if(window.__apdPanelTabsPatchLoaded) return;
  window.__apdPanelTabsPatchLoaded = true;

  const TAB_STORAGE_KEY='apd_panel_tab_v1';
  const TABS=[
    ['inicio','Inicio'],['alertas','Alertas'],['perfil','Listados'],['repo','Repositorio'],['plan','Plan'],['mercado','Estadísticas'],['preferencias','Preferencias'],['admin','Admin']
  ];
  const INTRO={
    alertas:['🔔','Alertas APD activas','Una bandeja clara para revisar oportunidades compatibles, publicaciones recientes y coincidencias con tu perfil docente.',['Oportunidades','Compatibilidad','Seguimiento']],
    perfil:['🪪','Listados y perfil docente','Datos personales, PID, cargos, materias y accesos rápidos para ordenar tu información docente.',['PID docente','Perfil','Listados']],
    repo:['📚','Repositorio docente PBA','Biblioteca de recursos, normativa, guías y materiales útiles para docentes y secretarías escolares.',['Normativa','Modelos','Guías']],
    plan:['💳','Mi plan y suscripción','Estado del plan, beneficios activos, vencimiento y opciones para actualizar o gestionar la suscripción.',['Plan activo','Beneficios','Pagos']],
    mercado:['📊','Radar docente PBA','Lectura rápida de movimiento provincial, distritos, cargos y tendencias para decidir mejor.',['Radar','Tendencias','Mercado']],
    preferencias:['⚙️','Preferencias de alertas','Configurá distritos, cargos, niveles, turnos y canales para que las alertas lleguen con más precisión.',['Distritos','Cargos','Canales']],
    admin:['🛠️','Administración','Acciones técnicas, pagos, usuarios, backfill, vista previa de alertas y controles internos.',['Usuarios','Pagos','Backfill']]
  };
  let booting=false, observer=null, adminObserver=null;

  function css(){
    if(document.getElementById('panel-tabs-patch-style')) return;
    const st=document.createElement('style');
    st.id='panel-tabs-patch-style';
    st.textContent=`
      :root{--apd-navy:#061a37;--apd-blue:#2454f5;--apd-line:#dbe7f5;--apd-text:#061a37;--apd-muted:#42526b;--apd-soft:#eef6ff}
      html{scroll-behavior:smooth}body{background:#f5f8ff!important;color:var(--apd-text)!important}.header{background:linear-gradient(135deg,#061a37,#0b2d5f)!important;box-shadow:0 16px 40px rgba(6,26,55,.18)!important;border-bottom:0!important;position:sticky;top:0;z-index:50}.header-inner{max-width:1180px!important;margin:0 auto!important;padding:14px 22px!important;gap:18px!important}.brand-icon{background:rgba(255,255,255,.12)!important;border-radius:14px!important}.brand-title{font-weight:900!important;letter-spacing:-.04em!important;color:#fff!important}.brand-sub{color:#bfd7ff!important}.top-nav{gap:10px!important;align-items:center!important;flex-wrap:wrap!important}.top-nav>a[href="./herramientas-docentes.html"],.top-nav>a[href="./licencias-docentes.html"]{display:none!important}#navPrivado{display:flex!important;gap:10px!important;align-items:center!important}#btnMiPanel{display:none!important}#btnCerrarSesion{border-radius:14px!important;background:#e22a2a!important;color:#fff!important;padding:11px 18px!important;border:0!important;font-weight:900!important}
      .apd-top-tabs{display:flex;gap:4px;align-items:center;flex-wrap:wrap;margin-right:4px}.apd-top-tab{position:relative;border:0;background:transparent;color:#eef5ff;padding:11px 10px;border-radius:0;font:inherit;font-size:13px;font-weight:800;cursor:pointer;opacity:.92}.apd-top-tab:hover{opacity:1;background:rgba(255,255,255,.08);border-radius:10px}.apd-top-tab.is-active{opacity:1;color:#fff}.apd-top-tab.is-active:after{content:'';position:absolute;left:10px;right:10px;bottom:-15px;height:3px;border-radius:999px;background:#2d61ff;box-shadow:0 0 18px rgba(45,97,255,.9)}.apd-top-tab.hidden{display:none!important}
      #panel-docente>.container{max-width:1180px!important;margin:0 auto!important;padding:26px 22px 0!important}.panel-header{display:none!important}.panel-tabs-wrap{max-width:1180px;margin:0 auto 18px;padding:0}.panel-tabs-nav{display:none!important}.panel-tab-pane{display:none}.panel-tab-pane.is-active{display:block}.panel-tab-grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:18px}.panel-tab-grid>.panel-card,.panel-tab-grid>#admin-panel-card{margin:0}.panel-tab-grid>.prefs-card{grid-column:1/-1}.panel-tab-grid>.panel-card:not([class*="span-"]){grid-column:span 12}
      .apd-panel-showcase{grid-column:1/-1!important;overflow:hidden;border-radius:16px!important;padding:0!important;background:#fff!important;border:1px solid var(--apd-line)!important;box-shadow:0 20px 55px rgba(16,36,61,.08)!important}.apd-hero-main{display:grid;grid-template-columns:1fr 1fr;gap:24px;align-items:center;padding:50px 46px 40px;background:linear-gradient(135deg,#fff 0%,#f8fbff 56%,#eef5ff 100%)}.apd-hero-copy{max-width:560px}.apd-panel-showcase h2{font-size:clamp(38px,5vw,60px);line-height:1.05;letter-spacing:-.055em;margin:0 0 18px;color:var(--apd-text)!important;font-weight:900;max-width:640px}.apd-panel-showcase h2 span{display:block;color:var(--apd-blue)}.apd-panel-showcase p{font-size:17px;line-height:1.56;color:#334761;margin:0 0 24px;max-width:540px}.apd-panel-showcase-actions{display:flex;gap:14px;flex-wrap:wrap}.apd-panel-showcase-actions a,.apd-tab-side a{display:inline-flex;align-items:center;justify-content:center;gap:8px;border-radius:12px;padding:14px 18px;text-decoration:none;font-weight:900;border:1px solid var(--apd-line);background:#fff;color:#0d1b35;box-shadow:0 12px 24px rgba(16,36,61,.07)}.apd-panel-showcase-actions a.primary,.apd-tab-side a:first-child{background:var(--apd-blue);color:#fff;border-color:var(--apd-blue);box-shadow:0 16px 32px rgba(36,84,245,.25)}
      .apd-hero-art{position:relative;min-height:310px;display:grid;place-items:center}.apd-monitor{position:relative;width:min(420px,100%);background:#e9edf5;border:8px solid #1b2535;border-radius:18px;padding:18px;box-shadow:0 28px 50px rgba(16,36,61,.22);transform:perspective(900px) rotateY(-4deg)}.apd-monitor:after{content:'';position:absolute;left:50%;bottom:-58px;width:86px;height:58px;background:linear-gradient(#bcc7d8,#edf2fb);transform:translateX(-50%);border-radius:0 0 14px 14px}.apd-monitor:before{content:'';position:absolute;left:50%;bottom:-74px;width:170px;height:18px;background:#cfd8e8;transform:translateX(-50%);border-radius:999px}.apd-monitor-top{background:#10244a;color:#fff;padding:8px 10px;border-radius:10px;font-size:11px;font-weight:900;margin-bottom:10px}.apd-monitor-row{display:grid;grid-template-columns:34px 1fr auto;gap:10px;align-items:center;background:#fff;border-radius:12px;margin:9px 0;padding:10px}.apd-monitor-row i{width:34px;height:34px;border-radius:11px;background:#eef4ff;display:grid;place-items:center;font-style:normal}.apd-monitor-line b{display:block;width:65%;height:9px;background:#dfe8fa;border-radius:999px;margin-bottom:6px}.apd-monitor-line span{display:block;width:44%;height:7px;background:#eef3fb;border-radius:999px}.apd-monitor-badge{background:var(--apd-blue);color:#fff;border-radius:999px;padding:3px 7px;font-size:10px;font-weight:900}.apd-float-bell{position:absolute;right:8px;top:18px;width:76px;height:76px;border-radius:18px;background:linear-gradient(135deg,#2454f5,#687cff);color:#fff;display:grid;place-items:center;font-size:34px;box-shadow:0 20px 44px rgba(36,84,245,.32)}.apd-float-bell:after{content:'1';position:absolute;right:-8px;top:-8px;width:24px;height:24px;border-radius:50%;background:#e72e36;color:#fff;display:grid;place-items:center;font-size:13px;font-weight:900;border:3px solid #fff}.apd-books{position:absolute;right:30px;bottom:14px;font-size:66px}.apd-plant{position:absolute;left:4px;bottom:28px;font-size:58px}
      .apd-panel-quick{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:18px;padding:30px 46px 28px;border-top:1px solid #edf2f8;background:#fff}.apd-panel-quick a{background:#fff;border:1px solid var(--apd-line);border-radius:18px;padding:18px 18px 20px;text-decoration:none;color:#10243d;box-shadow:0 10px 26px rgba(16,36,61,.05);transition:.16s}.apd-panel-quick a:hover{transform:translateY(-2px);box-shadow:0 16px 32px rgba(16,36,61,.10);border-color:#bcd2f0}.apd-panel-quick i{width:42px;height:42px;border-radius:14px;background:#eef6ff;display:grid;place-items:center;font-style:normal;font-size:23px;margin-bottom:14px}.apd-panel-quick b{display:block;margin-bottom:6px;color:var(--apd-text);font-size:16px}.apd-panel-quick span{display:block;color:#42526b;font-size:13px;line-height:1.38;min-height:34px}.apd-panel-quick em{display:inline-flex;margin-top:14px;color:var(--apd-blue);font-style:normal;font-weight:900;font-size:18px}
      .apd-panel-benefits,.apd-tab-intro{grid-column:1/-1!important;background:#fff!important;border:1px solid var(--apd-line)!important;border-radius:18px!important;box-shadow:0 18px 42px rgba(16,36,61,.05)!important}.apd-panel-benefits{padding:28px 46px!important}.apd-panel-benefits h3{margin:0 0 20px;font-size:25px;letter-spacing:-.04em;color:var(--apd-text)}.apd-benefit-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.apd-benefit{border-left:1px solid var(--apd-line);padding:0 20px}.apd-benefit:first-child{border-left:0;padding-left:0}.apd-benefit i{width:44px;height:44px;border-radius:14px;background:#eef6ff;display:grid;place-items:center;font-style:normal;font-size:24px;margin-bottom:12px}.apd-benefit b{display:block;margin-bottom:7px;color:var(--apd-text)}.apd-benefit span{font-size:13px;color:#42526b;line-height:1.45}
      .apd-tab-intro{position:relative;overflow:hidden;padding:26px 28px!important;background:linear-gradient(135deg,#fff,#f8fbff)!important;display:grid;grid-template-columns:1fr auto;gap:18px;align-items:center}.apd-tab-kicker{display:inline-flex;align-items:center;gap:8px;background:#edf4ff;color:#0f4fb8;border:1px solid #cfe1fa;border-radius:999px;padding:7px 11px;font-size:12px;font-weight:900;text-transform:uppercase;letter-spacing:.07em;margin-bottom:10px}.apd-tab-intro h2{font-size:clamp(28px,4vw,42px);line-height:1;letter-spacing:-.055em;margin:0 0 10px;color:var(--apd-text)}.apd-tab-intro p{margin:0;color:#42526b;font-size:15px;line-height:1.5;max-width:720px}.apd-tab-chips{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.apd-tab-chip{background:#eef6ff;color:#0f4fb8;border:1px solid #d5e7ff;border-radius:999px;padding:6px 10px;font-size:12px;font-weight:900}.apd-tab-side{display:flex;gap:10px;flex-wrap:wrap;justify-content:flex-end;align-items:center}.apd-tab-side a{font-size:13px;padding:11px 13px}
      .panel-card:not(.apd-panel-showcase):not(.apd-panel-benefits):not(.apd-tab-intro){border-radius:22px!important;border:1px solid var(--apd-line)!important;box-shadow:0 12px 30px rgba(16,36,61,.05)!important;background:#fff!important}.panel-card .card-lbl{font-weight:900!important;color:#0f3460!important;letter-spacing:.04em}.btn,.mini-btn{border-radius:12px!important;font-weight:900!important}.btn-primary{background:var(--apd-blue)!important;border-color:var(--apd-blue)!important;color:#fff!important;box-shadow:0 12px 26px rgba(36,84,245,.18)!important}.btn-secondary,.mini-btn{background:#eef3fb!important;color:#0f3460!important;border:1px solid var(--apd-line)!important}.footer{background:#061a37!important;margin-top:44px!important;padding:0!important}.footer-inner{max-width:1180px!important;margin:0 auto!important;color:#dbeafe!important;padding:28px 22px!important;line-height:1.8}.footer-inner a{color:#cfe0ff!important;text-decoration:none!important;font-weight:800!important}
      @media(max-width:1040px){.apd-top-tabs{order:3;width:100%;justify-content:center}.apd-top-tab.is-active:after{bottom:-4px}.apd-hero-main{grid-template-columns:1fr}.apd-hero-art{display:none}.apd-panel-quick{grid-template-columns:repeat(2,1fr)}.apd-benefit-grid{grid-template-columns:repeat(2,1fr)}.apd-tab-intro{grid-template-columns:1fr}.apd-tab-side{justify-content:flex-start}}
      @media(max-width:620px){#panel-docente>.container{padding:18px 14px 0!important}.apd-hero-main{padding:30px 22px}.apd-panel-showcase h2{font-size:36px}.apd-panel-quick{grid-template-columns:1fr;padding:22px}.apd-panel-benefits{padding:22px!important}.apd-benefit-grid{grid-template-columns:1fr}.apd-benefit{border-left:0;padding-left:0}.header-inner{padding:12px 14px!important}.apd-tab-intro{padding:22px!important}}
    `;
    document.head.appendChild(st);
  }

  function getContent(){return document.getElementById('panel-content');}
  function grid(k){return document.querySelector('#panel-tab-pane-'+k+' .panel-tab-grid');}

  function ensureHeaderTabs(){
    const nav=document.querySelector('.top-nav'); if(!nav) return;
    let h=document.getElementById('apd-top-tabs');
    if(!h){h=document.createElement('div');h.id='apd-top-tabs';h.className='apd-top-tabs';nav.insertBefore(h,document.getElementById('navPrivado')||nav.firstChild);}
    if(!h.dataset.ready){
      h.innerHTML=TABS.map(t=>'<button type="button" class="apd-top-tab" data-top-tab-key="'+t[0]+'">'+t[1]+'</button>').join('');
      h.dataset.ready='1';
      h.querySelectorAll('[data-top-tab-key]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();activateTab(b.dataset.topTabKey,{scrollTop:true});}));
    }
  }

  function ensureShell(){
    const c=getContent(); if(!document.getElementById('panel-docente')||!c) return;
    css(); ensureHeaderTabs();
    let w=document.getElementById('panel-tabs-wrap');
    if(!w){w=document.createElement('div');w.id='panel-tabs-wrap';w.className='panel-tabs-wrap';w.innerHTML='<div id="panel-tabs-nav" class="panel-tabs-nav"></div>'+TABS.map(t=>'<div id="panel-tab-pane-'+t[0]+'" class="panel-tab-pane"><div class="panel-tab-grid"></div></div>').join('');c.insertAdjacentElement('beforebegin',w);}
    const nav=w.querySelector('#panel-tabs-nav');
    if(nav&&!nav.dataset.ready){nav.innerHTML=TABS.map(t=>'<button type="button" class="panel-tab-btn" data-tab-key="'+t[0]+'">'+t[1]+'</button>').join('');nav.dataset.ready='1';nav.querySelectorAll('[data-tab-key]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();activateTab(b.dataset.tabKey,{scrollTop:true});}));}
    c.style.display='none';
  }

  function moveByContent(id,k){const el=document.getElementById(id), card=el&&el.closest('.panel-card'), g=grid(k); if(card&&g&&card.parentElement!==g) g.appendChild(card);}
  function moveById(id,k){const card=document.getElementById(id), g=grid(k); if(card&&g&&card.parentElement!==g) g.appendChild(card);}
  function movePrefs(){const card=document.querySelector('.prefs-card'), g=grid('preferencias'); if(card&&g&&card.parentElement!==g) g.appendChild(card);}

  function ensureShowcase(){
    const g=grid('inicio'); if(!g) return;
    let card=document.getElementById('apd-panel-showcase');
    if(!card){card=document.createElement('div');card.id='apd-panel-showcase';card.className='panel-card span-12 apd-panel-showcase';card.innerHTML='<div class="apd-hero-main"><div class="apd-hero-copy"><h2>Tu acceso rápido a la información <span>docente de PBA</span></h2><p>Alertas de Actos Públicos Digitales, análisis de cargos, herramientas y mucho más.</p><div class="apd-panel-showcase-actions"><a class="primary" href="#" data-apd-go-tab="alertas">🔔 Ver mis alertas</a><a href="#" data-apd-go-tab="inicio">▦ Ir al panel</a></div></div><div class="apd-hero-art"><div class="apd-plant">🪴</div><div class="apd-monitor"><div class="apd-monitor-top">🔔 APDocentePBA</div><div class="apd-monitor-row"><i>🔔</i><div class="apd-monitor-line"><b></b><span></span></div><em class="apd-monitor-badge">12</em></div><div class="apd-monitor-row"><i>📋</i><div class="apd-monitor-line"><b></b><span></span></div><em class="apd-monitor-badge">8</em></div><div class="apd-monitor-row"><i>🧰</i><div class="apd-monitor-line"><b></b><span></span></div><em class="apd-monitor-badge">Ver más</em></div></div><div class="apd-float-bell">🔔</div><div class="apd-books">📚</div></div></div><div class="apd-panel-quick"><a href="./como-funciona.html"><i>🔔</i><b>Cómo funciona</b><span>Conocé cómo funciona el sistema.</span><em>→</em></a><a href="./actos-publicos-digitales.html"><i>📋</i><b>APD</b><span>Actos Públicos Digitales.</span><em>→</em></a><a href="./pid-docente.html"><i>🎓</i><b>PID docente</b><span>Planilla de Inscripción Digital.</span><em>→</em></a><a href="./herramientas-docentes.html"><i>🧰</i><b>Herramientas</b><span>Recursos y utilidades para docentes.</span><em>→</em></a><a href="./licencias-docentes.html"><i>🧾</i><b>Licencias</b><span>Asistente de licencias docentes PBA.</span><em>→</em></a></div>';card.querySelector('[data-apd-go-tab="alertas"]').addEventListener('click',e=>{e.preventDefault();activateTab('alertas',{scrollTop:false});setTimeout(()=>document.getElementById('panel-alertas')?.scrollIntoView({behavior:'smooth',block:'start'}),120);});card.querySelector('[data-apd-go-tab="inicio"]').addEventListener('click',e=>{e.preventDefault();activateTab('inicio',{scrollTop:false});setTimeout(()=>document.getElementById('panel-datos-docente')?.scrollIntoView({behavior:'smooth',block:'start'}),120);});}
    if(card.parentElement!==g) g.prepend(card); else if(g.firstElementChild!==card) g.prepend(card);
  }

  function ensureBenefits(){
    const g=grid('inicio'); if(!g) return; let card=document.getElementById('apd-panel-benefits');
    if(!card){card=document.createElement('div');card.id='apd-panel-benefits';card.className='panel-card span-12 apd-panel-benefits';card.innerHTML='<h3>¿Qué podés hacer en APDocentePBA?</h3><div class="apd-benefit-grid"><div class="apd-benefit"><i>🔔</i><b>Recibí alertas</b><span>Nuevos actos públicos apenas se publican.</span></div><div class="apd-benefit"><i>🔎</i><b>Analizá cargos</b><span>Información clave para tomar mejores decisiones.</span></div><div class="apd-benefit"><i>📋</i><b>Organizá tu PID</b><span>Cargá y gestioná tu Planilla de Inscripción Digital.</span></div><div class="apd-benefit"><i>📊</i><b>Accedé a estadísticas</b><span>Datos actualizados para planificar tu carrera.</span></div></div>';}
    const hero=document.getElementById('apd-panel-showcase'); if(hero&&card.previousElementSibling!==hero) hero.insertAdjacentElement('afterend',card);
  }

  function ensureIntro(k){
    if(k==='inicio') return; const cfg=INTRO[k], g=grid(k); if(!cfg||!g) return; let card=document.getElementById('apd-tab-intro-'+k);
    if(!card){card=document.createElement('div');card.id='apd-tab-intro-'+k;card.className='panel-card span-12 apd-tab-intro';card.innerHTML='<div class="apd-tab-copy"><div class="apd-tab-kicker">'+cfg[0]+' '+cfg[1]+'</div><h2>'+cfg[1]+'</h2><p>'+cfg[2]+'</p><div class="apd-tab-chips">'+cfg[3].map(c=>'<span class="apd-tab-chip">'+c+'</span>').join('')+'</div></div><div class="apd-tab-side"><a href="#">Ver sección</a></div>';}
    if(card.parentElement!==g) g.prepend(card); else if(g.firstElementChild!==card) g.prepend(card);
  }

  function repartition(){
    ensureShell(); ensureShowcase(); ensureBenefits(); TABS.forEach(t=>ensureIntro(t[0]));
    moveByContent('panel-datos-docente','inicio');moveByContent('panel-preferencias-resumen','inicio');moveByContent('panel-plan','inicio');moveByContent('panel-canales','inicio');
    moveByContent('panel-alertas','alertas');moveByContent('panel-estadisticas','alertas');
    moveByContent('panel-perfil-docente','perfil');moveByContent('panel-listados-docente','perfil');moveById('panel-listados-pid-card','perfil');
    moveById('panel-repositorio-card','repo');moveById('panel-plan-selector-card','plan');moveByContent('panel-historico-apd','mercado');moveById('panel-radar-combinado-card','mercado');moveById('panel-radar-provincia','mercado');
    movePrefs();moveById('admin-panel-card','admin');moveByContent('panel-backfill-provincia','admin');refreshVisibility();
  }

  function hasCards(k){const g=grid(k); return !!(g&&[...g.children].some(el=>el instanceof HTMLElement&&!el.classList.contains('hidden')&&!(el.id==='admin-panel-card'&&el.classList.contains('hidden'))));}
  function refreshVisibility(){TABS.forEach(t=>{const visible=hasCards(t[0])||!!INTRO[t[0]]||t[0]==='inicio';document.querySelector('.panel-tab-btn[data-tab-key="'+t[0]+'"]')?.classList.toggle('hidden',!visible);document.querySelector('.apd-top-tab[data-top-tab-key="'+t[0]+'"]')?.classList.toggle('hidden',!visible);});activateTab(localStorage.getItem(TAB_STORAGE_KEY)||'inicio',{scrollTop:false});}
  function activateTab(k,opt){
    opt=opt||{}; const btn=document.querySelector('.apd-top-tab[data-top-tab-key="'+k+'"]:not(.hidden)')||document.querySelector('.panel-tab-btn[data-tab-key="'+k+'"]:not(.hidden)'); const fb=btn||document.querySelector('.apd-top-tab[data-top-tab-key]:not(.hidden)')||document.querySelector('.panel-tab-btn[data-tab-key]:not(.hidden)'); const key=(fb&&(fb.dataset.topTabKey||fb.dataset.tabKey))||k||'inicio';
    localStorage.setItem(TAB_STORAGE_KEY,key); TABS.forEach(t=>{document.querySelector('.panel-tab-btn[data-tab-key="'+t[0]+'"]')?.classList.toggle('is-active',t[0]===key);document.querySelector('.apd-top-tab[data-top-tab-key="'+t[0]+'"]')?.classList.toggle('is-active',t[0]===key);document.getElementById('panel-tab-pane-'+t[0])?.classList.toggle('is-active',t[0]===key);});
    if(opt.scrollTop) window.scrollTo({top:0,left:0,behavior:'auto'});
  }
  function boot(){ if(!document.getElementById('panel-docente')||!getContent()) return; if(!localStorage.getItem(TAB_STORAGE_KEY)) localStorage.setItem(TAB_STORAGE_KEY,'inicio'); repartition(); ensureFooter(); }
  function schedule(){ if(booting) return; booting=true; requestAnimationFrame(()=>{booting=false;boot();}); }
  function observers(){const c=getContent(); if(c&&!observer){observer=new MutationObserver(schedule);observer.observe(c,{childList:true});} const a=document.getElementById('admin-panel-card'); if(a&&!adminObserver){adminObserver=new MutationObserver(refreshVisibility);adminObserver.observe(a,{attributes:true,attributeFilter:['class']});}}
  function ensureFooter(){const f=document.querySelector('.footer-inner'); if(!f||f.dataset.visualReady) return; f.dataset.visualReady='1'; f.innerHTML='<div style="display:grid;grid-template-columns:1.4fr repeat(3,1fr);gap:22px;align-items:start"><div><strong style="font-size:20px;color:#fff">🔔 APDocentePBA</strong><p style="margin:8px 0;color:#b9d7ff">Alertas de Actos Públicos Digitales<br>Provincia de Buenos Aires</p></div><div><strong style="color:#fff">Navegación</strong><a href="#" data-apd-footer-tab="inicio">Inicio</a><a href="#" data-apd-footer-tab="alertas">Alertas</a><a href="#" data-apd-footer-tab="perfil">Listados</a><a href="#" data-apd-footer-tab="repo">Repositorio</a></div><div><strong style="color:#fff">Herramientas</strong><a href="./herramientas-docentes.html">Herramientas</a><a href="./licencias-docentes.html">Licencias</a><a href="./pid-docente.html">PID docente</a></div><div><strong style="color:#fff">Legal</strong><a href="./terminos.html">Términos</a><a href="./privacidad.html">Privacidad</a><a href="./suscripciones.html">Suscripciones</a><a href="./soporte.html">Soporte</a></div></div><div style="border-top:1px solid rgba(255,255,255,.12);margin-top:22px;padding-top:14px;text-align:center;color:#9fb9dc">© 2026 APDocentePBA. Todos los derechos reservados.</div>'; f.querySelectorAll('[data-apd-footer-tab]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();activateTab(a.dataset.apdFooterTab,{scrollTop:true});}));}

  window.APD_refreshPanelTabs=schedule;
  window.APD_activatePanelTab=function(key,userInitiated){activateTab(key,{scrollTop:!!userInitiated});};
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',()=>{schedule();observers();},{once:true}); else {schedule();observers();}
})();

(function(){
  'use strict';
  if(window.__apdAuthSessionPatchLoaderLoaded) return;
  window.__apdAuthSessionPatchLoaderLoaded=true;
  function load(){if(document.querySelector('script[data-apd-auth-session-patch="1"]')) return; const s=document.createElement('script');s.src='auth_session_patch.js?v=1';s.async=false;s.dataset.apdAuthSessionPatch='1';document.head.appendChild(s);}
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',load,{once:true}); else load();
})();