create table if not exists public.notification_delivery_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid null,
  channel text not null,
  event_type text not null,
  delivery_key text null,
  status text not null,
  provider text null,
  provider_message_id text null,
  plan_code text null,
  payload jsonb not null default '{}'::jsonb,
  error_message text null
);

create index if not exists notification_delivery_logs_created_at_idx
  on public.notification_delivery_logs (created_at desc);

create index if not exists notification_delivery_logs_user_id_idx
  on public.notification_delivery_logs (user_id);

create index if not exists notification_delivery_logs_channel_status_idx
  on public.notification_delivery_logs (channel, status);

create index if not exists notification_delivery_logs_delivery_key_idx
  on public.notification_delivery_logs (delivery_key);
